#!/usr/bin/env bash
# Create or replace an Ansible Inventory for an OpenWrt SSH target.

set -euo pipefail

usage() {
    cat <<'EOF'
Usage: ./configure-inventory.sh [options]

Options:
  --inventory FILE  Inventory file to write (default: inventory.ini)
  --host HOST       OpenWrt SSH host or IP address (default: 127.0.0.1)
  --port PORT       OpenWrt SSH port (default: 22)
  --key PATH        OpenWrt SSH private-key path (default: keys/openwrt_ed25519)
  --name NAME       Ansible host name (default: router)
  --known-hosts FILE  Use this dedicated SSH known-hosts file (optional)
  -h, --help        Show this help message

The inventory file is replaced on every successful invocation.
EOF
}

inventory_file='inventory.ini'
openwrt_host='127.0.0.1'
openwrt_ssh_port='22'
openwrt_ssh_key='keys/openwrt_ed25519'
host_name='router'
known_hosts_file=''

while [[ $# -gt 0 ]]; do
    case "$1" in
        --inventory|--host|--port|--key|--name|--known-hosts)
            [[ $# -ge 2 ]] || { echo "Error: $1 requires a value." >&2; exit 1; }
            case "$1" in
                --inventory) inventory_file="$2" ;;
                --host) openwrt_host="$2" ;;
                --port) openwrt_ssh_port="$2" ;;
                --key) openwrt_ssh_key="$2" ;;
                --name) host_name="$2" ;;
                --known-hosts) known_hosts_file="$2" ;;
            esac
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Error: unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

[[ -n "$openwrt_host" ]] || { echo 'Error: --host must not be empty.' >&2; exit 1; }
[[ "$openwrt_ssh_port" =~ ^[0-9]+$ ]] \
    && (( 10#$openwrt_ssh_port >= 1 && 10#$openwrt_ssh_port <= 65535 )) || {
    echo "Error: invalid SSH port: $openwrt_ssh_port" >&2
    exit 1
}
[[ "$host_name" =~ ^[A-Za-z0-9_.-]+$ ]] || {
    echo "Error: invalid host name: $host_name" >&2
    exit 1
}

inventory_dir="$(dirname "$inventory_file")"
[[ -d "$inventory_dir" ]] || { echo "Error: inventory directory does not exist: $inventory_dir" >&2; exit 1; }

if [[ -n "$known_hosts_file" ]]; then
    known_hosts_dir="$(dirname "$known_hosts_file")"
    [[ -d "$known_hosts_dir" ]] || { echo "Error: known-hosts directory does not exist: $known_hosts_dir" >&2; exit 1; }
    touch "$known_hosts_file"
fi

echo "Writing OpenWrt inventory: ${inventory_file}"
cat >"$inventory_file" <<EOF
# Generated by configure-inventory.sh. This file is replaced on each run.
[openwrt]
${host_name} ansible_host=${openwrt_host}

[openwrt:vars]
ansible_connection=ssh
ansible_user=root
ansible_port=${openwrt_ssh_port}
ansible_ssh_private_key_file=${openwrt_ssh_key}
# OpenWrt is managed with raw/script tasks and does not require Python.
ansible_python_interpreter=none
EOF

if [[ -n "$known_hosts_file" ]]; then
    cat >>"$inventory_file" <<EOF
# Keep this target's host key separate from the user's global known_hosts file.
ansible_ssh_common_args='-o UserKnownHostsFile=${known_hosts_file} -o StrictHostKeyChecking=accept-new'
EOF
else
    cat >>"$inventory_file" <<'EOF'
# Use the user's default ~/.ssh/known_hosts file and record newly seen keys.
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
EOF
fi

echo "Inventory ready: ${inventory_file}"
