# OpenWrt network configuration for a relay VM with one NIC:
#   eth0 = relay (10.8.7.4/20)

config interface 'loopback'
	option device 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config interface 'relay'
	option device 'eth0'
	option proto 'static'
	option ipaddr '10.8.7.4'
	option netmask '255.255.240.0'
	option gateway '10.8.1.254'
	list dns '1.1.1.1'

config route
	option interface 'relay'
	option target '10.8.24.0/22'
	option gateway '10.8.1.254'
	option metric '10'
