# OpenWrt network configuration for a QEMU VM with two NICs:
#   eth0 = WAN (DHCP client)
#   eth1 = LAN (10.8.7.3/20)

config interface 'loopback'
	option device 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config device
	option name 'br-lan'
	option type 'bridge'
	list ports 'eth1'

config interface 'lan'
	option device 'br-lan'
	option proto 'static'
	option ipaddr '10.8.7.3'
	option netmask '255.255.240.0'
	option ip6assign '60'

config route
	option interface 'lan'
	option target '10.8.24.0/22'
	option gateway '10.8.1.254'
	option metric '10'

config interface 'wan'
	option device 'eth0'
	option proto 'dhcp'
